### ISSUE TITLE
Message for BossSloth (not an issue just don't know how to contact you)

### ISSUE THREAD

**Issue by ShxDowXD** [tddebart/BossSlothsMods#16]
Hello, I really love mods for ROUNDS and im really inspired by the cards you make and the maps you imported from stickfight.
I really want to have ago at making my own cards or maps but cannot find any tutorials on how to do so.

Do you think you can give me a link or some tips for how to create rounds cards mods, maybe a software to do so or something? It would help me out so much

Good luck on all your projects as well!

Thanks,
ShxDowXD

**Comment by tddebart** [comment]
Join the rounds modding community https://discord.gg/zUtsjXWeWk there are all the mod creators where you can also ask them questions.
If you wanna start with mod creations then take a look into the #mod-dev-faq channel there are most of the steps to start modding

**Comment by ShxDowXD** [comment]
Thanks so much!
